version: '3.7'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node
    restart: always
    ports:
      - 3030:3030
    volumes:
      - ./:/usr/src/app
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_DATABASE=todo_db
      - PORT=3000
    networks:
      - todo_network
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: todo_db
    networks:
      - todo_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - todo_network

volumes:
  node:
    driver: local

networks:
  todo_network:
    driver: bridge
